openapi: 3.1.0
info:
  title: Bybit GPT Testnet API
  version: 1.0.0
  description: Минималистичный API для покупки, продажи и получения баланса через Bybit Testnet

servers:
  - url: https://bybit-gpt-1.onrender.com

paths:
  /portfolio:
    get:
      summary: Получить баланс
      operationId: getPortfolio
      responses:
        '200':
          description: Баланс аккаунта
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                  retCode:
                    type: integer
                  retMsg:
                    type: string
                required: [retCode, result]

  /buy:
    post:
      summary: Купить монету
      operationId: buyAsset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                amount:
                  type: number
                quote:
                  type: number
              required: [symbol]
      responses:
        '200':
          description: Результат покупки
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                  retCode:
                    type: integer
                  retMsg:
                    type: string
                required: [retCode, result]

  /sell:
    post:
      summary: Продать монету
      operationId: sellAsset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                amount:
                  type: number
                quote:
                  type: number
              required: [symbol]
      responses:
        '200':
          description: Результат продажи
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                  retCode:
                    type: integer
                  retMsg:
                    type: string
                required: [retCode, result]


  /pnl:
    get:
      summary: Доходность портфеля
      operationId: getPnL
      responses:
        '200':
          description: PnL аккаунта
          content:
            application/json:
              schema:
                type: object
                properties:
                  initial_usd:
                    type: number
                  current_usd:
                    type: number
                  pnl_usd:
                    type: number
                  pnl_percent:
                    type: number
                required: [initial_usd, current_usd, pnl_usd, pnl_percent]














