openapi: 3.0.0
info:
  title: Bybit GPT-1 API
  version: 1.0.0

servers:
  - url: https://bybit-gpt-1.onrender.com

paths:
  /portfolio:
    get:
      summary: Получить баланс непустых монет (Bybit Testnet)
      operationId: getPortfolio
      responses:
        '200':
          description: Баланс счета
          content:
            application/json:
              schema:
                type: object

  /buy:
    get:
      summary: Маркет-ордер на покупку BTC за 100 USDT
      operationId: buyBTC
      responses:
        '200':
          description: Информация об ордере на покупку
          content:
            application/json:
              schema:
                type: object

  /sell:
    get:
      summary: Маркет-ордер на продажу 0.01 ETH
      operationId: sellETH
      responses:
        '200':
          description: Информация об ордере на продажу
          content:
            application/json:
              schema:
                type: object


