# openapi.yaml
openapi: 3.1.0
info:
  title: Bybit Crypto Assistant API
  version: 1.0.0
  description: API для работы с портфелем и торговлей на Bybit Testnet
servers:
  - url: https://bybit-gpt-1.onrender.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /portfolio:
    get:
      summary: Баланс портфеля
      description: Получить текущие балансы портфеля через Bybit Testnet
      responses:
        '200':
          description: Балансы портфеля
          content:
            application/json:
              schema:
                type: object
  /buy:
    post:
      summary: Купить по рынку
      description: Осуществить рыночную покупку по заданному символу и сумме (в котируемой валюте)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                amount:
                  type: number
              required:
                - symbol
                - amount
      responses:
        '200':
          description: Результат покупки
          content:
            application/json:
              schema:
                type: object
  /sell:
    post:
      summary: Продать по рынку
      description: Осуществить рыночную продажу по заданному символу и сумме (в базовой валюте)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                amount:
                  type: number
              required:
                - symbol
                - amount
      responses:
        '200':
          description: Результат продажи
          content:
            application/json:
              schema:
                type: object
  /pnl:
    get:
      summary: Расчет PnL
      description: Получить текущий PnL (разница между начальным и текущим балансом)
      responses:
        '200':
          description: Значение PnL
          content:
            application/json:
              schema:
                type: object
                properties:
                  pnl:
                    type: number
