openapi: 3.0.0
info:
  title: Bybit Crypto Assistant API
  version: 1.1.0
  description: Торговля на Bybit Spot — лимитные и рыночные ордера
servers:
  - url: https://bybit-gpt-1.onrender.com

paths:
  /buy:
    post:
      summary: Купить актив (Limit или Market)
      operationId: buyAsset
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeRequest'
      responses:
        '200':
          description: Результат покупки
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeResponse'

  /sell:
    post:
      summary: Продать актив (Limit или Market)
      operationId: sellAsset
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeRequest'
      responses:
        '200':
          description: Результат продажи
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    TradeRequest:
      type: object
      required:
        - symbol
        - amount
      properties:
        symbol:
          type: string
          example: "BTCUSDT"
        amount:
          type: number
          example: 0.01
        price:
          type: number
          example: 30000

    TradeResponse:
      type: object
      properties:
        order:
          type: object
        message:
          type: string


