openapi: 3.0.0
info:
  title: Bybit Spot Trading API
  version: '1.1'
  description: |
    API для торговли спотом на Bybit. Требуется Bearer-токен для доступа.
servers:
  - url: https://bybit-gpt-1.onrender.com

paths:
  /buy:
    post:
      summary: Купить актив
      description: |
        Размещает ордер на покупку (Market или Limit).
        Требуется токен авторизации (Bearer).
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeRequest'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeResponse'
        '400':
          description: Ошибка запроса (например, неверный параметр или ограничения Bybit)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Ошибка авторизации (невалидный токен)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /sell:
    post:
      summary: Продать актив
      description: |
        Размещает ордер на продажу (Market или Limit).
        Требуется токен авторизации (Bearer).
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeRequest'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeResponse'
        '400':
          description: Ошибка запроса (например, неверный параметр или ограничения Bybit)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Ошибка авторизации (невалидный токен)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Bearer
  schemas:
    TradeRequest:
      type: object
      required:
        - symbol
        - quantity
        - orderType
      properties:
        symbol:
          type: string
          description: Торговая пара, например BTCUSDT
        quantity:
          type: number
          format: float
          description: Количество базового актива для ордера
        orderType:
          type: string
          enum: [Market, Limit]
          description: Тип ордера: `Market` или `Limit`
        price:
          type: number
          format: float
          description: Цена за единицу (обязательно для `Limit`, игнорируется для `Market`)
    TradeResponse:
      type: object
      properties:
        order_id:
          type: string
          description: Идентификатор созданного ордера
        status:
          type: string
          description: Статус ордера (например, `Created`, `Rejected` и т.д.)
        executed_qty:
          type: number
          format: float
          description: Фактически исполненное количество
        executed_price:
          type: number
          format: float
          description: Цена исполнения (для рыночных ордеров фактическая цена, иначе та, что была указана)
    BuyResponse:
      allOf:
        - $ref: '#/components/schemas/TradeResponse'
      description: Ответ на запрос /buy
    SellResponse:
      allOf:
        - $ref: '#/components/schemas/TradeResponse'
      description: Ответ на запрос /sell
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Описание ошибки

security:
  - bearerAuth: []

