openapi: 3.0.0
info:
  title: Bybit Unified API
  version: "1.0"
  description: API для торговли, просмотра баланса и расчета PnL на Bybit через Unified Account.
servers:
  - url: https://bybit-gpt-1.onrender.com
paths:
  /portfolio:
    get:
      summary: Получить баланс активов
      operationId: get_portfolio
      description: Возвращает список монет с ненулевым балансом на спотовом счёте.
      responses:
        '200':
          description: Список активов
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    coin:
                      type: string
                    free:
                      type: number
                    locked:
                      type: number
                    total:
                      type: number
                  required: [coin, free, locked, total]

  /buy:
    post:
      summary: Рыночная покупка монеты
      operationId: buy_coin
      description: Совершает рыночную покупку актива по заданному символу и количеству.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                  example: BTCUSDT
                amount:
                  type: number
                  example: 0.01
              required: [symbol, amount]
      responses:
        '200':
          description: Ответ от Bybit API
          content:
            application/json:
              schema:
                type: object

  /sell:
    post:
      summary: Рыночная продажа монеты
      operationId: sell_coin
      description: Совершает рыночную продажу актива по заданному символу и количеству.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                  example: BTCUSDT
                amount:
                  type: number
                  example: 0.01
              required: [symbol, amount]
      responses:
        '200':
          description: Ответ от Bybit API
          content:
            application/json:
              schema:
                type: object

  /pnl:
    get:
      summary: Расчёт PnL
      operationId: get_pnl
      description: Возвращает прибыль/убыток по сравнению с начальными значениями портфеля.
      responses:
        '200':
          description: Значения PnL
          content:
            application/json:
              schema:
                type: object
                properties:
                  initial_balance:
                    type: number
                  current_balance:
                    type: number
                  pnl:
                    type: number
                required: [initial_balance, current_balance, pnl]

