openapi: 3.0.0
info:
  title: "API торговли на Bybit Spot"
  version: "1.0.0"
  servers:
    - url: https://bybit-gpt-1.onrender.com
paths:
  /buy:
    post:
      summary: "Купить (Buy) выбранный символ"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                  description: "Тикер валютной пары (например, BTCUSDT)"
                amount:
                  type: number
                  description: "Количество монет для покупки/продажи"
                price:
                  type: number
                  description: "Цена для лимитного ордера (если указана, ордер будет Limit)."
              required:
                - symbol
                - amount
      responses:
        '200':
          description: "Информация о размещенном ордере"
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    type: object
                    description: "Полный ответ от Bybit с информацией о ордере"
                  message:
                    type: string
                    description: "Сообщение о статусе операции"
  /sell:
    post:
      summary: "Продать (Sell) выбранный символ"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                  description: "Тикер валютной пары (например, BTCUSDT)"
                amount:
                  type: number
                  description: "Количество монет для покупки/продажи"
                price:
                  type: number
                  description: "Цена для лимитного ордера (если указана, ордер будет Limit)."
              required:
                - symbol
                - amount
      responses:
        '200':
          description: "Информация о размещенном ордере"
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    type: object
                    description: "Полный ответ от Bybit с информацией о ордере"
                  message:
                    type: string
                    description: "Сообщение о статусе операции"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

