openapi: 3.1.0
info:
  title: Bybit Crypto Assistant API
  version: 1.1.0
  description: API для торговли любыми монетами на Bybit Spot (маркет и лимитные ордера).
servers:
  - url: https://bybit-gpt-1.onrender.com
    description: Render production server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TradeRequest:
      type: object
      required:
        - symbol
        - quantity
        - orderType
      properties:
        symbol:
          type: string
          example: "ADAUSDT"
        quantity:
          type: number
          format: float
          example: 100.0
        orderType:
          type: string
          enum: [Market, Limit]
          example: "Market"
        price:
          type: number
          format: float
          nullable: true
          example: 0.45
    TradeResponse:
      type: object
      properties:
        orderId:
          type: string
        status:
          type: string
        qty:
          type: number
          format: float
        price:
          type: number
          format: float
          nullable: true
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string

paths:
  /buy:
    post:
      operationId: buyAsset
      summary: Рыночная или лимитная покупка
      description: Размещает ордер на покупку (поддерживает Market и Limit).
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeRequest'
      responses:
        '200':
          description: Ордер на покупку успешно размещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeResponse'
        '400':
          description: Ошибка параметров или ограничений
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sell:
    post:
      operationId: sellAsset
      summary: Рыночная или лимитная продажа
      description: Размещает ордер на продажу (поддерживает Market и Limit).
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeRequest'
      responses:
        '200':
          description: Ордер на продажу успешно размещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeResponse'
        '400':
          description: Ошибка параметров или ограничений
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
